### ISSUE TITLE
Flight planning: Finalize flight booking

### ISSUE THREAD

**Issue by J-C-V** [MetaEMK/FGK_PASMAS_frontend#15]
### User Story

As a seller ...
... I would like to finalize the booking / planning process based on my prior passenger and flight selection ...
... in order to sell the flights to customers.

### ToDos

- [ ] Mockup
- [x] Frontend implementation

### Acceptance Criteria

- [x] I can see an overview of my prior selection / reservation
  - [x] I can see all passengers who I created
  - [x] I can see the reserved flight which I selected
- [x] I can confirm the booking process
  - [x] I have to fill in all missing fields before I can confirm the booking
- [x] I can see the ticket number after confirming the booking / planning process 
- [x] I can start a new booking / planning process after seeing the ticket number

**Comment by J-C-V** [comment]
mockups have low priority atm, won't be added
