### ISSUE TITLE
Flight planning: Passenger view

### ISSUE THREAD

**Issue by MetaEMK** [MetaEMK/FGK_PASMAS_frontend#2]
## User Story
As a seller ...
... I would like to create several passengers (weight) as part of the flight planning ...
... in order to display the various flight options in a later view

## TODOs
- [x] Mockup
- [x] Frontend Implementation

## Acceptance criteria
- [x] I can create at least 1 passenger with first name, last name (optional) and weight (mandatory)
- [x] I can edit or delete the passengers I have created
- [x] I can select the different divisions (fligh types)
- [x] I can only create a passenger list with the maximum number of passengers allowed on the flight type
- [x] I can click on a button if at least one passanger is created and get to the `Flight planning: Flight Selection` view
