### ISSUE TITLE
Flight planning: Flight Selection

### ISSUE THREAD

**Issue by MetaEMK** [MetaEMK/FGK_PASMAS_frontend#7]
## User Story
As a seller ...
... I would like to see all possible flight slots for a pre-defined flight type (see #2) ...
... in order to reserve a flight slot for my customers

## TODOs
- [x] Mockup
- [x] Frontend Implementation (Prototype)

## Acceptance criteria
- [x] I can see every possible flight slot for this flight type
   - [x] I can see the estimated departure time (EDT)
   - [x] I can see the estimated payload
   - [x] I can see if the plane is able to start (overload)
   - [x] I can see information about the plane (registration)
- [x] I can click the virtual flight slot and open the reservation page
- [x] This view is updated in realtime

**Comment by MetaEMK** [comment]
![Image](https://github.com/MetaEMK/FGK_PASMAS_frontend/assets/23456557/9984504a-71ec-4be4-8136-164a207a9cc9)

**Comment by J-C-V** [comment]
implemented
